version: '3.2'
services:
  app:
    build: .
    image: ${USER}/personal-metrics
    restart: always
    ports:
      - target: $APP_PORT
        published: $APP_PORT
        protocol: tcp
        mode: host
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
  grafana:
    image: "grafana/grafana"
    restart: always
    ports:
      - target: 3000
        published: $GRAFANA_PORT
        protocol: tcp
        mode: host
    volumes:
      - ${XDG_DATA_HOME:-~/.local/share}/personal-metrics/grafana:/var/lib/grafana
    depends_on:
      - postgres
  postgres:
    image: "timescale/timescaledb:latest-pg11"
    restart: always
    ports:
      - target: 5432
        published: $DB_PORT
        protocol: tcp
        mode: host
    volumes:
      - ${XDG_DATA_HOME:-~/.local/share}/personal-metrics/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
