version: '3'
services:
  personal-metrics:
    build: .
    restart: always
    ports:
     - "9000:9000"
  grafana:
    image: "grafana/grafana"
    restart: always
    ports:
     - "9001:9001"
  postgres:
    image: "timescale/timescaledb:latest-pg11"
    restart: always
