version: '3.2'
services:
  app:
    container_name: personal-metrics
    image: adamvig/personal-metrics:latest
    restart: always
    ports:
      - target: $APP_PORT
        published: $APP_PORT
        protocol: tcp
        mode: host
    depends_on:
      - postgres
    env_file:
      - .env
    labels:
      - "traefik.http.routers.personalmetrics.entrypoints=websecure"
      - "traefik.http.routers.personalmetrics.rule=Host(`personal-metrics.adamvig.com`)"
      - "traefik.http.routers.personalmetrics.tls=true"
      - "traefik.http.routers.personalmetrics.tls.certresolver=le"
  grafana:
    container_name: personal-metrics-grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - target: 3000
        published: $GRAFANA_PORT
        protocol: tcp
        mode: host
    volumes:
      - ${XDG_DATA_HOME:-~/.local/share}/personal-metrics/grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL:-http://localhost:9001}
    depends_on:
      - postgres
    labels:
      - "traefik.http.routers.personalmetricsgrafana.entrypoints=websecure"
      - "traefik.http.routers.personalmetricsgrafana.rule=Host(`personal-metrics.adamvig.com`)"
      - "traefik.http.routers.personalmetricsgrafana.tls=true"
      - "traefik.http.routers.personalmetricsgrafana.tls.certresolver=le"
  postgres:
    container_name: personal-metrics-postgres
    image: timescale/timescaledb:latest-pg11
    restart: always
    ports:
      - target: 5432
        published: $DB_PORT
        protocol: tcp
        mode: host
    volumes:
      # Use named volume to work around Docker for Windows bug (https://stackoverflow.com/a/49920624/1850656)
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
