version: '3'
services:
  personal-metrics:
    build: .
    restart: always
    ports:
      - 9000:9000
  grafana:
    image: "grafana/grafana"
    restart: always
    ports:
      - 3000:9001
  postgres:
    image: "timescale/timescaledb:latest-pg11"
    restart: always
    ports:
      - 5432:9002
    volumes:
      - ${XDG_DATA_HOME:?XDG_DATA_HOME must be set in env}/personal-metrics/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=personal-metrics
      - PGDATA=/var/lib/postgresql/data/pgdata
