version: '3.2'
services:
  app:
    image: 'adamvig/personal-metrics'
    restart: always
    ports:
      - target: $APP_PORT
        published: $APP_PORT
        protocol: tcp
        mode: host
    depends_on:
      - postgres
    env_file:
      - .env
  grafana:
    image: 'grafana/grafana'
    restart: always
    ports:
      - target: 3000
        published: $GRAFANA_PORT
        protocol: tcp
        mode: host
    volumes:
      - ${XDG_DATA_HOME:-~/.local/share}/personal-metrics/grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL:-http://localhost:9001}
    depends_on:
      - postgres
  postgres:
    image: 'timescale/timescaledb:latest-pg11'
    restart: always
    ports:
      - target: 5432
        published: $DB_PORT
        protocol: tcp
        mode: host
    volumes:
      # Use named volume to work around Docker for Windows bug (https://stackoverflow.com/a/49920624/1850656)
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
